version: '3.5'

networks:
  malcolm_network:
    external: true

services:
  logs_web:
    container_name: logs_web
    build: .
    restart: always
    volumes:
      - .:/opt/app
      - /opt/app/node_modules
    ports:
      - 5005:5000
      - 3003:3000
    depends_on:
      - logs_db
      - logs_rabbitmq
    networks:
      - malcolm_network
  logs_db:
    container_name: logs_db
    image: mongo:latest
    restart: always
    volumes:
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
      - db-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${DATABASE_NAME}
    ports:
      - 27018:27017
    networks:
      - malcolm_network
  logs_rabbitmq:
    container_name: logs_rabbitmq
    image: rabbitmq:3.6-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - malcolm_network

volumes:
  db-data: